spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aicryptoadvisor
    username: aicryptoadvisor
    password: aicryptoadvisor

logging:
  level:
    com.moveo.aicryptoadvisor: DEBUG
    org.flywaydb: INFO
